language: python
python:
  - 3.6
sudo: false
install:
  - travis_retry pip install .
  - travis_retry pip install pytest-cov coverage coveralls
script:
  - coverage run --source=social-media-count setup.py
after_success:
  coveralls